import type { Metadata } from "next";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import { AuthProvider } from "@/context/AuthContext";
import { UrlProvider } from "@/context/UrlContext";



export const metadata: Metadata = {
  title: "Partes Diarios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <UrlProvider>
    <html id='__next' lang="en" >
       <link rel="manifest" href="/manifest.json" />
      <body
        className="bg-blue-200"
      >
        {children}
      </body>
    </html>
    </UrlProvider>
    </AuthProvider>
  );
}
