import type { Metadata } from "next";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import { AuthProvider } from "@/context/AuthContext";
import { UrlProvider } from "@/context/UrlContext";
import { AnimatePresence } from "framer-motion";



export const metadata: Metadata = {
  title: "Partes Diarios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <UrlProvider>
      <AnimatePresence mode="wait">
    <html id='__next' lang="en" >
       <link rel="manifest" href="/manifest.json" />     
      <body
        style={{backgroundColor: '#E3D5DF'}}
      >
        {children}
      </body>
    </html>
    </AnimatePresence>
    </UrlProvider>
    </AuthProvider>
  );
}
